<h2>Customer</h2>
<table>
    <tr>
        <th>Avatar</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        
    </tr>
    
    
        <tr>
            <td>Avatar</td>
            <td><?php echo $block->getFirstname() ?></td>
            <td><?php echo $block->getLastname() ?></td>
            <td><?php echo $block->getEmail() ?></td>
        </tr>
        
</table>
